# Variables to access as {{ site.<var> }}
title: Mohammed Kassahun 
email: info@mohammedkn.com
description: A graduate of mathematics working on security and exploitation in Ethiopia. Learning and writing about web application to become full stack engineer or to die trying. Being sick of fancy design, I am building problem solver application and participating on problem solving challenges and projects such as Icoglab, google challenge and project Euler.

baseurl: "" 
url: "https://mohammedkn.com"
permalink: /:title

facebook_username: mohammedkn
github_username:  mhmmdkn
twitter_username: mohammedkn


markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

paginate: 12
paginate_path: "posts/page:num/"


exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

